### PR TITLE
Implement RangerReader, also fixed some test problems

### LINKED ISSUE #23: recordio.Reader should be independent with the concept of chunk
Currently 

https://github.com/ElasticDL/pyrecordio/blob/develop/recordio/recordio/reader.py#L6

However, chunk is a concept must be hidden from the end-users. `recordio.Reader` should provide an interface of reading a range of records, instead of chunks.

### PR DESCRIPTION
**Pull request by zou000**
fix #23

### CODE REVIEW

**Review by wangkuiyi — APPROVED** [review]
Super efficient! @zou000 .

Please @yuyicg have a look.

**Comment by skydoorkai** [comment]
RangerReader supports one file data range read, not multiple files?
So data should be stored in one recordio file, or if multiple files are used, each worker can only access one file for each task?

**Comment by zou000** [comment]
> RangerReader supports one file data range read, not multiple files?
> So data should be stored in one recordio file, or if multiple files are used, each worker can only access one file for each task?

Yes. One task should not span multiple files.

**Comment by wangkuiyi** [comment]
I think @skydoorkai posed a good question. It is very likely that we need a RangeReader that can read a range that span over more than one ReocrdIO files. I think we can merge this PR first, then think of this new MergedRangeReader class. What do you think @zou000 @skydoorkai ?

**Comment by zou000** [comment]
> I think @skydoorkai posed a good question. It is very likely that we need a RangeReader that can read a range that span over more than one ReocrdIO files. I think we can merge this PR first, then think of this new MergedRangeReader class. What do you think @zou000 @skydoorkai ?

The RecordIO class is designed around a single file, in this class we don' t need to consider multiple file issues.  If we need multiple file support, we can compose several individual RangeReader into a merged one, providing same interface.

**Pull request merged**
